name: Lint

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          jupyter: false
          version: "24.8.0"

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install -r requirements-dev.txt
      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install isort
        run: pip install -r requirements-dev.txt
      - name: Run isort
        run: isort src -l 120 --check
